name: Build and test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: insper-embarcados/pico-build@v0

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install wokwi-cli
        run: |
          wget -q -O /usr/local/bin/wokwi-cli https://raw.githubusercontent.com/rafaelcorsi/wokwi-cli/main/scripts/install.sh
          chmod +x /usr/local/bin/wokwi-cli

      - name: run test
        env: WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        run: |
          pytest
